### ISSUE TITLE
can't access my wallet

### ISSUE THREAD

**Issue by angryuser777** [hivewallet/hive-js#236]
I can't access my wallet since two days ago. I have tried everything. (clearing browser's cache, restarting pin, etc) also I've tried the new version on https://hive-js.herokuapp.com
 i always get this error:

![issue](https://cloud.githubusercontent.com/assets/12495147/7679775/4ccb0a2a-fd75-11e4-92b2-551014b1f2f2.JPG)

I'm sure my pass phrase is correct and I've checked it using: https://dcpos.github.io/bip39/
also i was able to create a new wallet and access it without any issues.

**Comment by w-hive** [comment]
Hi there, I think we finally may have some idea of what this is. Would you mind emailing w@hivewallet.com about this? We'd like to include your wallet in the diagnosis pool, if possible.

**Comment by w-hive** [comment]
Related to:

https://github.com/hivewallet/hive-js/issues/233#issuecomment-113821036

**Comment by w-hive** [comment]
Please try http://hive-js.herokuapp.com with your passphrase and let us know if it works.

**Comment by mbz6720** [comment]
I tried still cannot send

**Comment by w-hive** [comment]
@mbz6720 cannot _send_? Do you get the error message shown above? If not, that is a different issue, and I would ask that you open another ticket about it with as much detail as you can.

**Comment by mbz6720** [comment]
ok im going to open another ticket right now sorry I definitely clicked the wrong issue and responded

**Comment by mbz6720** [comment]
hello i cannot send from my hive litecoin web wallet or ios wallet from my
iphone i first had this problem when i tried to send a transaction for
about 99 ltc the ltc were taken out of my hive wallet and i checked the
transaction on block explorer and got 0 confirmations after about 4 hours i
checked again still no confirmations a short time later i opened my hive
wallet on my iphone and noticed the 99 ltc i sent out were back in there
and i could find no record of the transaction in my wallet history or
anywhere and i did not save the transaction id ever since then i have not
been able to send anything from my wallet although it can recieve i sent
from another wallet to see if i could recieve which i could the error i am
getting is transaction failed please make sure you are connectd to the
internet ive also tried the staging site for hive and nothing is working
the time of the transaction i sent out that got rejected was approx. 2 pm
friday july 10th

**Comment by w-hive** [comment]
Closing this and other redundant issues now; #237 and #239 exist to consolidate the timing issues. You guys may continue to comment here however.
